# Generated by Django 3.1.7 on 2022-05-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20220507_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
